// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMut6H0NKRnAVtGjzI8gEmiRuOwdRhJME',
    appId: '1:1034085346908:android:3c6c27ec4a05a765c44099',
    messagingSenderId: '1034085346908',
    projectId: 'feira-de-compras',
    storageBucket: 'feira-de-compras.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqmozgCSJPAn61_Vbus6nEQb_YcY1_fpc',
    appId: '1:1034085346908:ios:d9fad87f45ad3f14c44099',
    messagingSenderId: '1034085346908',
    projectId: 'feira-de-compras',
    storageBucket: 'feira-de-compras.appspot.com',
    iosBundleId: 'com.example.feiraDeCompras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqmozgCSJPAn61_Vbus6nEQb_YcY1_fpc',
    appId: '1:1034085346908:ios:7033b064e92c6773c44099',
    messagingSenderId: '1034085346908',
    projectId: 'feira-de-compras',
    storageBucket: 'feira-de-compras.appspot.com',
    iosBundleId: 'com.example.feiraDeCompras.RunnerTests',
  );
}
